import type { Metadata } from "next";
import { Inter, Lato, Montserrat_Alternates } from "next/font/google";
import "./globals.css";
import clsx from "clsx";

const lato = Lato({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-lato",
  weight: ["400", "700"]
});

const monstserratAlternates = Montserrat_Alternates({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-montserrat-alternates",
  weight: ["400", "600"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={clsx(lato.variable,  monstserratAlternates.variable)}
    >
      <body>
        {children}
      </body>
    </html>
  );
}
